# Generated by Django 5.0.6 on 2024-07-06 14:16

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Personne",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("NNI", models.CharField(max_length=20, unique=True)),
                ("numero_tel", models.CharField(max_length=15)),
                ("date_naissance", models.DateField()),
                ("img", models.ImageField(upload_to="images/")),
                ("lieu_naissance_ar", models.CharField(max_length=100)),
                ("lieu_naissance_fr", models.CharField(max_length=100)),
                ("nationalite_iso", models.CharField(max_length=3)),
                ("nom_famille_ar", models.CharField(max_length=100)),
                ("nom_famille_fr", models.CharField(max_length=100)),
                ("prenom_ar", models.CharField(max_length=100)),
                ("prenom_fr", models.CharField(max_length=100)),
                ("prenom_pere_ar", models.CharField(max_length=100)),
                ("prenom_pere_fr", models.CharField(max_length=100)),
                ("sexe_fr", models.CharField(max_length=1)),
            ],
        ),
    ]
